---
cache:
  directories:
    - $HOME/.m2
  pip: true

branches:
  only:
    - master
    - /^travis.*/
    - /^v.*/

stages:
  - name: test
  - name: deploy
    if: branch = master AND type != pull_request

jobs:
  include:

    # Kotlin/Java

    - stage: test
      language: java
      jdk: openjdk9

      before_script:
        - cd client-kotlin-java

      install: skip
      after_success: bash <(curl -s https://codecov.io/bash) -F kotlinjava -f ./client-kotlin-java/target/site/jacoco/jacoco.xml

    - stage: deploy
      language: java
      jdk: openjdk9

      before_script:
        - cd client-kotlin-java

      script: skip
      install: skip
      deploy:
        - provider: script
          script: mvn --settings .maven.xml site -DskipTests=true -B && git add dokka
          on:
            tags: true
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          verbose: true
          local_dir: ./dokka
          on:
            tags: true

    - stage: deploy
      language: java
      jdk: openjdk9

      before_script:
        - cd client-kotlin-java
      before_install:
        - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
        - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

      script: skip
      install: skip
      deploy:
        - provider: script
          script: mvn deploy --settings .maven.xml -DskipTests=true -B
          on:
            branch: master

    # C++

    - stage: test
      language: c++

      before_script:
        - cd client-c++

      script:
        - mkdir -p build/run
        - cd build/run
        - cmake ../..

    # Python

    - stage: test
      language: python
      python: 3.7

      before_script:
        - cd client-python3

      install: pip install tox tox-travis coverage
      script: tox
      after_success: bash <(curl -s https://codecov.io/bash) -F python3 -s ./client-python3
