flags:
  - kotlinjava:
      paths: client-kotlin-java
  - cpp:
      paths: client-c++
  - python3:
      paths: client-python3
  - go:
      paths: client-go
  - ruby:
      paths: client-ruby
  - dart:
      paths: client-dart
  - rust:
      paths: client-rust