name: animatedledstripclient
description: Client library for connecting to an AnimatedLEDStripServer
# version: 1.0.0
homepage: https://github.com/AnimatedLEDStrip
author: Max Narvaez <mnmax.narvaez3@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
